# Generated by Django 5.0.6 on 2024-07-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedsearch',
            name='query',
            field=models.TextField(max_length=1000),
        ),
    ]
