# Generated by Django 5.0.6 on 2024-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_alter_advancedsearch_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsearch',
            name='name',
            field=models.CharField(default='Query', max_length=64),
            preserve_default=False,
        ),
    ]
