"""
Django's settings for pov_manager project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os

import environ
from pathlib import Path

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=str,
    CLIENT_ID=str,
    CLIENT_SECRET=str,
    MONGO_HOST=str,
    MONGO_PORT=int,
    MONGO_USER=str,
    MONGO_PASSWORD=str,
    MICROSOFT_AUTH_ENABLED=(bool, False),
    MICROSOFT_AUTH_CLIENT_ID=str,
    MICROSOFT_AUTH_CLIENT_SECRET=str,
    MICROSOFT_AUTH_TENANT_ID=str,
    XDR_DEFAULT_REGION=str,
    VDR_ACCESS_TOKEN=str,
    VDR_TEAM_ID=str,
    CTU_ACCESS_TOKEN=str,
    CTU_REPORTS_PATH=str,
    CTU_BASE_URL=str,
    CACHE_TENANTS_DATA_COLLECTION_NAME=(str, 'tenants'),
    CACHE_TENANTS_STATS_COLLECTION_NAME=(str, 'stats_tenants'),
    DMARC_LAMBDA_FUNCTION_NAME=str,
    DMARC_LAMBDA_REGION=str
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from repo root (parent of this Django project) and/or next to manage.py
for _env_path in (BASE_DIR.parent / '.env', BASE_DIR / '.env'):
    if _env_path.is_file():
        environ.Env.read_env(_env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://*.secureworks.net', 'https://*.127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third party
    # 'bootstrap5',
    'django_extensions',
    'microsoft_auth',

    # POV Manager
    'core',
    'orchestrator',
    'vdr',
    'xdr',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pov_manager.urls'

_base_context_processors = [
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
]
if env('MICROSOFT_AUTH_ENABLED'):
    # Avoid NoReverseMatch for 'auth-callback' on email login when Microsoft OAuth is off
    _base_context_processors.append('microsoft_auth.context_processors.microsoft')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': _base_context_processors,
        },
    },
]

WSGI_APPLICATION = 'pov_manager.wsgi.application'

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    'core.email_authentication.EmailAuthentication',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': env.db()
}

# MongoDB client
MONGO_HOST = env('MONGO_HOST')
MONGO_PORT = env('MONGO_PORT')
MONGO_USER = env('MONGO_USER')
MONGO_PASSWORD = env('MONGO_PASSWORD')
MONGO_DB_NAME = env('MONGO_DB_NAME')

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = True

XDR_DEFAULT_REGION = env('XDR_DEFAULT_REGION')

VDR_ACCESS_TOKEN = env('VDR_ACCESS_TOKEN')
VDR_TEAM_ID = env('VDR_TEAM_ID')
CTU_ACCESS_TOKEN = env('CTU_ACCESS_TOKEN')
# Docker Compose mounts ./ctu-reports at /ctu-reports. Running manage.py on the host
# often has no writable /ctu-reports — fall back to the same repo directory the mount uses.
_ctu_reports_env = env('CTU_REPORTS_PATH')
_ctu_reports_path = Path(_ctu_reports_env)
if _ctu_reports_env == '/ctu-reports' and (
    not _ctu_reports_path.is_dir() or not os.access(_ctu_reports_path, os.W_OK)
):
    CTU_REPORTS_PATH = str((BASE_DIR.parent / 'ctu-reports').resolve())
else:
    CTU_REPORTS_PATH = _ctu_reports_env
CTU_BASE_URL = env('CTU_BASE_URL')

CACHE_TENANTS_DATA_COLLECTION_NAME = env('CACHE_TENANTS_DATA_COLLECTION_NAME')
CACHE_TENANTS_STATS_COLLECTION_NAME = env('CACHE_TENANTS_STATS_COLLECTION_NAME')

# Cache configuration
# Using LocMemCache for simplicity (no database table required)
# For multi-process deployments, consider using Redis or database cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pov-manager-cache',
    }
}

# SE Email cache settings
SE_EMAIL_CACHE_KEY = 'vdr_se_emails_list'
SE_EMAIL_CACHE_TIMEOUT = 60 * 60 * 24  # 24 hours

# Cache configuration
# Using LocMemCache for simplicity (no database table required)
# For multi-process deployments, consider using Redis or database cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pov-manager-cache',
    }
}

# SE Email cache settings
SE_EMAIL_CACHE_KEY = 'vdr_se_emails_list'
SE_EMAIL_CACHE_TIMEOUT = 60 * 60 * 24  # 24 hours

DMARC_LAMBDA_FUNCTION_NAME = env('DMARC_LAMBDA_FUNCTION_NAME')
DMARC_LAMBDA_REGION = env('DMARC_LAMBDA_REGION')

MICROSOFT_AUTH_ENABLED = env('MICROSOFT_AUTH_ENABLED')

if not MICROSOFT_AUTH_ENABLED:
    # django-microsoft-auth defaults LOGIN_ENABLED True; avoid W003/W004 when OAuth is unused
    MICROSOFT_AUTH_LOGIN_ENABLED = False

if MICROSOFT_AUTH_ENABLED:
    MICROSOFT_AUTH_CLIENT_ID = env('MICROSOFT_AUTH_CLIENT_ID')
    MICROSOFT_AUTH_CLIENT_SECRET = env('MICROSOFT_AUTH_CLIENT_SECRET')
    MICROSOFT_AUTH_TENANT_ID = env('MICROSOFT_AUTH_TENANT_ID')
    MICROSOFT_AUTH_LOGIN_TYPE = "ma"
    MICROSOFT_AUTH_EXTRA_SCOPES = "User.Read"

    AUTHENTICATION_BACKENDS.append('core.backends.CustomMicrosoftBackend')
