# Generated by Django 4.2 on 2023-05-23 16:01

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_url', models.URLField(blank=True, null=True)),
                ('organization_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=200, null=True), size=None)),
                ('ip_ranges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None)),
                ('se_email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
