# Generated by Django 4.2 on 2023-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
