# Generated by Django 4.2 on 2023-05-25 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0002_threatprofile_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='organization_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
