# Generated by Django 4.2 on 2023-05-25 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0003_alter_threatprofile_organization_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='ip_ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
