# Generated by Django 4.2 on 2023-05-25 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0004_alter_threatprofile_ip_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='ip_ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='threatprofile',
            name='organization_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
