# Generated by Django 4.2 on 2023-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0006_threatprofile_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Profile created'), ('TAG_CREATED', 'VDR Tag created'), ('SCANS_SCHEDULED', 'Scans scheduled')], default='CREATED', max_length=50),
        ),
    ]
