# Generated by Django 4.2.1 on 2023-06-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0007_threatprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cve_number', models.CharField(blank=True, max_length=50, null=True)),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('vulnerability_id', models.CharField(blank=True, max_length=50, null=True)),
                ('score_cvss', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_cps', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('group_description', models.TextField(blank=True, max_length=300, null=True)),
                ('group_differentiator', models.CharField(blank=True, max_length=200, null=True)),
                ('os_family', models.CharField(blank=True, max_length=50, null=True)),
                ('os_name', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('server', 'Server'), ('website', 'Website')], max_length=20, null=True)),
                ('threat_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdr.threatprofile')),
            ],
        ),
    ]
