# Generated by Django 4.2.1 on 2023-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0008_vulnerabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilities',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
