# Generated by Django 4.2.1 on 2023-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0011_alter_threatprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='ctu_autobrief_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
