# Generated by Django 4.2.1 on 2023-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0012_threatprofile_ctu_autobrief_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Profile created'), ('TAG_CREATED', 'VDR Tag created'), ('SCANS_SCHEDULED', 'Scans scheduled'), ('VULNERABILITY_RESULTS_COLLECTED', 'Vulnerability results collected'), ('VULNERABILITY_RESULTS_PROCESSED', 'Vulnerability results processed'), ('CTU_AUTOBRIEF_DATA_PROCESSED', 'CTU Autobrief data processed')], default='CREATED', max_length=50),
        ),
    ]
