# Generated by Django 4.2.1 on 2023-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0013_alter_threatprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='ctu_autobrief_report_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='threatprofile',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Profile created'), ('TAG_CREATED', 'VDR Tag created'), ('SCANS_SCHEDULED', 'Scans scheduled'), ('VULNERABILITY_RESULTS_COLLECTED', 'Vulnerability results collected'), ('VULNERABILITY_RESULTS_PROCESSED', 'Vulnerability results processed'), ('CTU_AUTOBRIEF_DATA_PROCESSED', 'CTU Autobrief data processed'), ('CTU_AUTOBRIEF_REPORT_REQUESTED', 'CTU Autobrief report requested')], default='CREATED', max_length=50),
        ),
    ]
