# Generated by Django 4.2.1 on 2023-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0014_threatprofile_ctu_autobrief_report_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatprofile',
            name='organization_url',
        ),
        migrations.AddField(
            model_name='threatprofile',
            name='organization_email_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
