# Generated by Django 4.2.1 on 2023-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0015_remove_threatprofile_organization_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Profile created'), ('TAG_CREATED', 'VDR Tag created'), ('SCANS_SCHEDULED', 'Scans scheduled'), ('VULNERABILITY_RESULTS_COLLECTED', 'Vulnerability results collected'), ('VULNERABILITY_RESULTS_PROCESSED', 'Vulnerability results processed'), ('CTU_AUTOBRIEF_DATA_PROCESSED', 'CTU Autobrief data processed'), ('CTU_AUTOBRIEF_REPORT_REQUESTED', 'CTU Autobrief report requested'), ('CTU_AUTOBRIEF_REPORT_AVAILABLE', 'CTU Autobrief report available')], default='CREATED', max_length=50),
        ),
    ]
