# Generated by Django 4.2.1 on 2023-06-14 14:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0016_alter_threatprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='organization_email_domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
