# Generated by Django 4.2.1 on 2023-06-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0017_alter_threatprofile_organization_email_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatprofile',
            old_name='organization_email_domain',
            new_name='organization_email_domains',
        ),
    ]
