# Generated by Django 4.2.1 on 2023-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0018_rename_organization_email_domain_threatprofile_organization_email_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
