# Generated by Django 4.2.18 on 2025-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0019_alter_vulnerabilities_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Profile created'), ('TAG_CREATED', 'VDR Tag created'), ('SCANS_SCHEDULED', 'Scans scheduled'), ('VULNERABILITY_RESULTS_COLLECTED', 'Vulnerability results collected'), ('VULNERABILITY_RESULTS_PROCESSED', 'Vulnerability results processed'), ('CTU_AUTOBRIEF_DATA_PROCESSED', 'CTU Autobrief data processed'), ('CTU_AUTOBRIEF_REPORT_REQUESTED', 'CTU Autobrief report requested'), ('CTU_AUTOBRIEF_REPORT_AVAILABLE', 'CTU Autobrief report available'), ('CTU_AUTOBRIEF_REPORT_REQUESTED_WITHOUT_VDR', 'CTU Autobrief report requested without VDR'), ('CTU_AUTOBRIEF_REPORT_AVAILABLE_WITHOUT_VDR', 'CTU Autobrief report available without VDR')], default='CREATED', max_length=50),
        ),
    ]
