# Generated by Django 4.2.18 on 2025-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0021_threatprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='vivun_activity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
