# Generated by Django 4.2.18 on 2025-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0022_threatprofile_vivun_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatprofile',
            name='vivun_activity',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
