# Generated by Django 4.2.18 on 2025-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0023_alter_threatprofile_vivun_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='os_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
