# Generated by Django 4.2.18 on 2025-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0024_alter_vulnerabilities_os_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
