# Generated by Django 5.2.4 on 2026-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdr', '0028_threatprofile_ai_exposure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatprofile',
            name='ai_exposure_job_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatprofile',
            name='ai_exposure_job_status',
            field=models.CharField(blank=True, choices=[('', 'Not set (legacy)'), ('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('skipped', 'Skipped (no domain)')], default='', help_text='Background AI exposure job state for CTU autobrief alignment', max_length=20),
        ),
    ]
